### ISSUE TITLE
should it also hide the parent Block?

### ISSUE THREAD

**Issue by samumist** [cgkineo/adapt-hide#1]
When a full-width component is set to `_hideOn`, it leaves an empty block which breaks the flow of the page. 

For example, in the screenshot, when the text component was hide on large screen, it left its parent block empty.
![screenshot 2016-09-23 00 17 26](https://cloud.githubusercontent.com/assets/3883086/18756680/627fe0ba-8123-11e6-918f-55ead89e7da3.jpg)
### Hide the Text Component

![screenshot 2016-09-23 00 17 52](https://cloud.githubusercontent.com/assets/3883086/18756688/691f7b9c-8123-11e6-9248-b394798a6a36.jpg)

Should the parent block also be set to `display: none`?

**Comment by oliverfoster** [comment]
you should be able to use adapt-hide on the block @samumist

**Comment by samumist** [comment]
Yeah, I didn't think of that. Silly me!

**Comment by oliverfoster** [comment]
it's alright, it wasn't in the readme that you could until today 👍
